name: Lint
on:
  push:
    branches-ignore:
      - "master"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Vale
        uses: errata-ai/vale-action@v1.0.2
        with:
          styles: |
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            https://github.com/ConsenSys/Style-Guide/raw/master/consensys.zip
          config: https://raw.githubusercontent.com/ConsenSys/Style-Guide/master/.vale.ini
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
